# Service registers under this name
spring:
  application:
    name: microservice-consumer

# Discovery Server Access
#eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8080
